# Generated by Django 5.0.3 on 2024-04-17 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nimapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created_by',
        ),
    ]
