# Generated by Django 5.0.3 on 2024-05-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nimapp', '0005_alter_project_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.CharField(max_length=255),
        ),
    ]
